### PR TITLE
Some animation stuff

### PR DESCRIPTION
**Pull request by CerBor**
This PR adds animation for texts in the main menu.

### CODE REVIEW

**Comment by prokube** [comment]
they're boppin'

i'd recommend changing the time to, like, `Conductor.crochet` so it bops to the beat

**Comment by CerBor** [comment]
Oh, good idea, I will probably try it

**Comment by Gui-iago** [comment]
checks failed

**Comment by CerBor** [comment]
I accidentaly ```FlxTween.tween``` instead of ```FlxTween.angle```

**Comment by Gui-iago** [comment]
gonna wait for at least 1 check to finish, then I merge this

**Pull request merged**
