### PR TITLE
Marvelous Ratings

### PR DESCRIPTION
**Pull request by TahirArch**
Yea, I added marvelous rating.
It is optional tho.

### CODE REVIEW

**Comment by Gui-iago** [comment]
gonna wait for the checks, if everything is good, I'm merging this

**Comment by TahirArch** [comment]
> gonna wait for the checks, if everything is good, I'm merging this

its broken right now, sorry. forgot some codes

**Comment by Gui-iago** [comment]
> > gonna wait for the checks, if everything is good, I'm merging this
> 
> its broken right now, sorry. forgot some codes

take you time, I usually also make mistakes like that

**Comment by TahirArch** [comment]
> > > gonna wait for the checks, if everything is good, I'm merging this
> > 
> > 
> > its broken right now, sorry. forgot some codes
> 
> take you time, I usually also make mistakes like that

yea it should be fixed right now

**Pull request merged**
