### PR TITLE
Add ability to disable camera note movements

### PR DESCRIPTION
**Pull request by CerBor**
This PR adds ability to choose, do you want to use camera movements from arrows.

### CODE REVIEW

**Comment by Gui-iago** [comment]
if I ever manage to get in contact with you anywhere, I'd like to know if you wanna work on the project, of course on the separate one since this one is pretty much fucked at this point and I really wanna rework on it

**Comment by CerBor** [comment]
Hello, sorry for long replying ~~(just checked my email)~~. I think, I can. Never work on someone other project on github before, but why not

**Comment by Gui-iago** [comment]
> Hello, sorry for long replying ~(just checked my email)~. I think, I can. Never work on someone other project on github before, but why not

sure, I will invite you to the new github

**Comment by CerBor** [comment]
OK, I got it, thank you

**Pull request merged**
